### ISSUE TITLE
font-patcher: not enough value to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by durka** [ryanoasis/nerd-fonts#1142]
#### 🗹 Requirements

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [x] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

#### 🎯 Subject of the issue

Experienced behavior:

I ran the font patcher script on a standard Ubuntu font and it did not complete.

```
$ python3 ./font-patcher /usr/share/fonts/truetype/ubuntu/UbuntuMono-R.ttf
Nerd Fonts Patcher v2.3.3 (3.5.1) executing
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
  Ignoring 'VDMX' vertical device metrics table
The glyph named fi is mapped to U+F001.
But its name indicates it should be mapped to U+FB01.
The glyph named fl is mapped to U+F002.
But its name indicates it should be mapped to U+FB02.
The glyph named Omega is mapped to U+03A9.
But its name indicates it should be mapped to U+2126.
('period', (1.0, 0.0, 0.0, 1.0, 0.0, 0.0))
('period', (1.0, 0.0, 0.0, 1.0, 0.0, 323.0))
Traceback (most recent call last):
  File "/tmp/FontPatcher/./font-patcher", line 1732, in <module>
    main()
  File "/tmp/FontPatcher/./font-patcher", line 1712, in main
    patcher.patch(sourceFonts[-1])
  File "/tmp/FontPatcher/./font-patcher", line 268, in patch
    self.get_essential_references()
  File "/tmp/FontPatcher/./font-patcher", line 948, in get_essential_references
    self.add_glyphrefs_to_essential(glyph)
  File "/tmp/FontPatcher/./font-patcher", line 935, in add_glyphrefs_to_essential
    for refcode in [ self.sourceFont[n].unicode for n, m, s in references ]:
  File "/tmp/FontPatcher/./font-patcher", line 935, in <listcomp>
    for refcode in [ self.sourceFont[n].unicode for n, m, s in references ]:
ValueError: not enough values to unpack (expected 3, got 2)
```

Changing the referenced line from `n, m, s` to `n, m` appears to fix the issue on my machine.

Expected behavior:

I expected the script to patch the font.

Example symbols:

N/A

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_
   - /usr/share/fonts/truetype/ubuntu/UbuntuMono-R.ttf
- _Where did you get the file from (download link, self patched, source downloaded from link...)_
   - Came with Ubuntu, specifically the `fonts-ubuntu` package
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_
   - Kitty, but that didn't come into play here
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_
   - Pop!_OS 22.04

#### ★ Screenshots (Optional)

Confirmed that the patching worked after I made the change described above.

![image](https://user-images.githubusercontent.com/47007/223934758-f28748b2-f9c6-4588-8af7-0c95f95d510c.png)

**Comment by Finii** [comment]
Sorry to hear of the problem, thanks for reporting!

Can you tell me which version of Fontforge you are using?

**Comment by durka** [comment]
I have `fonttools`4.0.2 installed through pip3 and this stuff installed through apt:
```
fontforge-common/jammy,jammy,now 1:20201107~dfsg-4build1 all [installed,automatic]
fontforge/jammy,now 1:20201107~dfsg-4build1 amd64 [installed]
libfontforge4/jammy,now 1:20201107~dfsg-4build1 amd64 [installed,automatic]
python3-fontforge/jammy,now 1:20201107~dfsg-4build1 amd64 [installed]
```

**Comment by Finii** [comment]
Thanks for the details. Lets see

```
$ fontforge ./font-patcher /usr/share/fonts/truetype/ubuntu/UbuntuMono-R.ttf 2>/dev/null
Nerd Fonts Patcher v2.3.3-77 (3.5.11) (ff 20230101) executing
Adding 179 Glyphs from Seti-UI + Custom Set
╢████████████████████████████████████████╟ 100%
Adding 6 Glyphs from Heavy Angle Brackets Set
╢████████████████████████████████████████╟ 100%
Adding 198 Glyphs from Devicons Set
╢████████████████████████████████████████╟ 100%
Done with Patch Sets, generating font...
{'fontname': 'UbuntuMono-Regular', 'fullname': 'Ubuntu Mono', 'familyname': 'Ubuntu Mono'}
Can not handle font flags (PermissionError(13, 'Permission denied'))
   Ubuntu Mono Nerd Font
   \===> 'Ubuntu Mono Nerd Font.ttf'
```
_HEAD font-patcher and latest `fontforge`_

(Oh there is another bug, but that is unrelated.)

Seems to work. Going back to your font-patcher version.

```
$ fontforge ./font-patcher /usr/share/fonts/truetype/ubuntu/UbuntuMono-R.ttf 2>/dev/null
Nerd Fonts Patcher v2.3.3 (3.5.1) executing
Adding 177 Glyphs from Seti-UI + Custom Set 
╢████████████████████████████████████████╟ 100%
Adding 198 Glyphs from Devicons Set 
╢████████████████████████████████████████╟ 100%
Done with Patch Sets, generating font...
Can not handle font flags (PermissionError(13, 'Permission denied'))
   Ubuntu Mono Nerd Font
   \===> 'Ubuntu Mono Nerd Font.ttf'
```

Hmm, going back in `fontforge`...

```
$ cd ~/git/fontforge
$ git checkout 20201107
$ rm -Rf build
$ mkdir build
$ cd build
$ cmake -GNinja ..
$ ninja
$ cd ~/git/nerd-fonts
$ fontforge ./font-patcher /usr/share/fonts/truetype/ubuntu/UbuntuMono-R.ttf
Copyright (c) 2000-2023. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20201107
 Based on sources from 2023-03-10 09:19 UTC-ML-D-GDK3.
 Based on source from git with hash: 21ad4a18fb3d4becfe566d8215eba4483b0ddc4b
Nerd Fonts Patcher v2.3.3 (3.5.1) executing
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
  Ignoring 'VDMX' vertical device metrics table
The glyph named fi is mapped to U+F001.
  But its name indicates it should be mapped to U+FB01.
The glyph named fl is mapped to U+F002.
  But its name indicates it should be mapped to U+FB02.
The glyph named Omega is mapped to U+03A9.
  But its name indicates it should be mapped to U+2126.
Traceback (most recent call last):
  File "/home/fini/extra/git/nerd-fonts/./font-patcher", line 1730, in <module>
    main()
  File "/home/fini/extra/git/nerd-fonts/./font-patcher", line 1710, in main
    patcher.patch(sourceFonts[-1])
  File "/home/fini/extra/git/nerd-fonts/./font-patcher", line 268, in patch
    self.get_essential_references()
  File "/home/fini/extra/git/nerd-fonts/./font-patcher", line 946, in get_essential_references
    self.add_glyphrefs_to_essential(glyph)
  File "/home/fini/extra/git/nerd-fonts/./font-patcher", line 933, in add_glyphrefs_to_essential
    for refcode in [ self.sourceFont[n].unicode for n, m, s in references ]:
  File "/home/fini/extra/git/nerd-fonts/./font-patcher", line 933, in <listcomp>
    for refcode in [ self.sourceFont[n].unicode for n, m, s in references ]:
ValueError: not enough values to unpack (expected 3, got 2)
```

Ah okay, that changed in `fontforge`. Fixing...

**Comment by Finii** [comment]
Thanks again for reporting!
Maybe we should add such a font (i.e. maybe just exactly that) to the workflow tests? Hmm. Lets see if the font is available in the github workflow VM.
