### ISSUE TITLE
Font patcher error with Noto Sans CJK

### ISSUE THREAD

**Issue by shiro** [ryanoasis/nerd-fonts#412]
Hello, I'm trying to patch Noto Sans CJK JP, but the script dies every time, it worked fine on Droid Sans for reference.
Here's the dumped stack trace:

```
No glyph with unicode U+051a4 in font
... (lots of same errors) ...
No glyph with unicode U+05be7 in font
No glyph with unicode U+05c60 in font
No glyph with unicode U+06753 in font
No glyph with unicode U+06eba in font
No glyph with unicode U+07c3e in font
Traceback (most recent call last):
  File "font-patcher", line 896, in <module>
    main()
  File "font-patcher", line 890, in main
    patcher = font_patcher()
  File "font-patcher", line 55, in __init__
    self.setup_font_names()
  File "font-patcher", line 267, in setup_font_names
    fullname = self.sourceFont.fullname + verboseAdditionalFontNameSuffix
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

NOTE: I'm on manjaro linux and am using the latest patcher from git.

any help is greatly appreciated!

#### 🔧 Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_ Noto Sans CJK JP
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ st
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ Manjaro linux

**Comment by onokatio** [comment]
I have same problem.

**Comment by onokatio** [comment]
This patch fixes the problem temporary. But it is probaly fontforge's bug.

```
diff --git a/font-patcher b/font-patcher
index ac2d6390..44695119 100755
--- a/font-patcher
+++ b/font-patcher
@@ -52,6 +52,10 @@ class font_patcher:
         self.setup_arguments()
         self.config = configparser.ConfigParser(empty_lines_in_values=False, allow_no_value=True)
         self.sourceFont = fontforge.open(self.args.font)
+        if(self.sourceFont.fullname == None):
+            self.sourceFont.fullname = self.sourceFont.fontname
+        if(self.sourceFont.version == None):
+            self.sourceFont.version = ""
         self.setup_font_names()
         self.remove_ligatures()
         make_sure_path_exists(self.args.outputdir)

```

**Comment by shiro** [comment]
I tried the patch, but I just get a different error now:
```
...
No glyph with unicode U+06753 in font
No glyph with unicode U+06eba in font
No glyph with unicode U+07c3e in font
Traceback (most recent call last):
  File "font-patcher", line 912, in <module>
    main()
  File "font-patcher", line 906, in main
    patcher = font_patcher()
  File "font-patcher", line 69, in __init__
    self.extension = os.path.splitext(self.sourceFont.path)[1]
  File "/usr/lib/python3.8/posixpath.py", line 118, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
Your help is much appreciated!

**Comment by ryanoasis** [comment]
FYI, #720 merged
