### ISSUE TITLE
Error when using --careful

### ISSUE THREAD

**Issue by gregf** [ryanoasis/nerd-fonts#45]
Running The following produces a error.

```
./font-patcher -s --fontawesome --octicons --pomicons --powerline --powerlineextra --careful PragamataPro.ttf

updating glyph: <Glyph Branch in font PragmataProNerdFontCompleteMono> Branch putting at: E0A0
updating glyph: <Glyph LN in font PragmataProNerdFontCompleteMono> LN putting at: E0A1
updating glyph: <Glyph padlock_closed in font PragmataProNerdFontCompleteMono> padlock_closed putting at: E0A2
updating glyph: <Glyph HardRightArrow in font PragmataProNerdFontCompleteMono> HardRightArrow putting at: E0B0
updating glyph: <Glyph SoftRightArrow in font PragmataProNerdFontCompleteMono> SoftRightArrow putting at: E0B1
updating glyph: <Glyph HardLeftArrow in font PragmataProNerdFontCompleteMono> HardLeftArrow putting at: E0B2
updating glyph: <Glyph SoftLeftArrow in font PragmataProNerdFontCompleteMono> SoftLeftArrow putting at: E0B3
updating glyph: <Glyph uniE0A3 in font DroidSansMonoForPowerlinePlusNerdFileTypesMono> uniE0A3 putting at: uniE0A3
Traceback (most recent call last):
  File "./font-patcher", line 423, in <module>
    copy_glyphs(sourceFont, symbolsPowerlineExtraRange1Start, symbolsPowerlineExtraRange1End, powerlineExtraSymbols, symbolsPowerlineExtraRange1Start, symbolsPowerlineExtraRange1End, True)
  File "./font-patcher", line 327, in copy_glyphs
    codepoint = int("0x" + copiedToSlot, 16)
ValueError: invalid literal for int() with base 16: '0xuniE0A3'
```

Running the same line without --careful it completes without error.

**Comment by ryanoasis** [comment]
@gregf Thanks! Workin' on it :relaxed:
