### ISSUE TITLE
font-patcher fails to patch InputMono [original-source.otf, does not exist]

### ISSUE THREAD

**Issue by pfr-dev** [ryanoasis/nerd-fonts#666]
#### 🎯 Subject of the issue

I encounter the following issue when trying to patch InputMono fonts:

```
λ ~/Downloads/Fonts/Input_Fonts/Input fontforge -script ./font-patcher --careful --complete  --progressbars --mono Input-Regular_\(InputMono-Regular\).ttf
Copyright (c) 2000-2021. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20201107
 Based on sources from 2021-09-20 10:22 UTC-ML-D-GDK3.
 Based on source from git with hash: 5bbc0e0406fb04e9f9ae419cd1d8ed9864b18f7e
The glyph named Tcommaaccent is mapped to U+021A.
  But its name indicates it should be mapped to U+0162.
The glyph named Delta is mapped to U+0394.
  But its name indicates it should be mapped to U+2206.
The glyph named Omega is mapped to U+03A9.
  But its name indicates it should be mapped to U+2126.
The glyph named tcommaaccent is mapped to U+021B.
  But its name indicates it should be mapped to U+0163.
The glyph named mu is mapped to U+03BC.
  But its name indicates it should be mapped to U+00B5.
The requested file, original-source.otf, does not exist
Traceback (most recent call last):
  File "/home/david/Downloads/Fonts/Input_Fonts/Input/./font-patcher", line 929, in <module>
    main()
  File "/home/david/Downloads/Fonts/Input_Fonts/Input/./font-patcher", line 924, in main
    patcher.patch()
  File "/home/david/Downloads/Fonts/Input_Fonts/Input/./font-patcher", line 88, in patch
    symfont = fontforge.open(self.args.glyphdir + patch['Filename'])
OSError: Open failed
```

#### 🔧 Your Setup

Pop!_OS 21.04
Alacritty
zsh

**Comment by Finii** [comment]
I guess you do not have the source fonts (*) in `src/` available?
They are expected in a subdir relative to the location where the patcher script is in.
Or specify an option:
```
--glyphdir
        default=__dir__ + "/src/glyphs/"
        help='Path to glyphs to be used for patching
```

(*) The fonts with the symbols that are to be added to InputMono, i.e. https://github.com/ryanoasis/nerd-fonts/tree/master/src

**Comment by Finii** [comment]
The file is in the repo, where it belongs: https://github.com/ryanoasis/nerd-fonts/tree/master/src/glyphs

Please check that the file is existing in `src/glyphs/` relative to the `font-patcher` scriptfile location.

**Comment by pfr-dev** [comment]
Not to worry, I've since distro-hopped over to Void Linux and it appears that InputMono infact does supports glyphs. So no longer an issue.
