### ISSUE TITLE
Font-patcher fails to patch font: OSError

### ISSUE THREAD

**Issue by ExperiBass** [ryanoasis/nerd-fonts#686]
#### 🗹 Requirements

- [x] A brief but descriptive _title_ of your issue
- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my issue and found nothing related and/or helpful
- [x] I have read or scanned the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] I have read or scanned the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### 🎯 Subject of the issue

I'm attempting to patch a font I have, but the script fails with this error:
```
fontforge -script ./font-patcher ./Bicubik-capital.otf -out ./ -l --fontawesomeextension --fontawesome --fontlinux --octicons --powersymbols --pomicons --powerline --powerlineextra --material --weather
Copyright (c) 2000-2021. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20201107
 Based on sources from 2021-11-16 19:50 UTC-ML-D-GDK3.
 Based on source from git with hash: 58238cc173c80379d0d4616971fc793da26c6aa4
This font contains both a 'kern' table and a 'GPOS' table.
  The 'kern' table will only be read if there is no 'kern' feature in 'GPOS'.
Traceback (most recent call last):
  File "/home/gingka/Builds/nerd-fonts/./font-patcher", line 936, in <module>
    main()
  File "/home/gingka/Builds/nerd-fonts/./font-patcher", line 930, in main
    patcher = font_patcher()
  File "/home/gingka/Builds/nerd-fonts/./font-patcher", line 54, in __init__
    self.sourceFont = fontforge.open(self.args.font)
OSError: Open failed
```

#### 🔧 Your Setup

- _Which font are you using (e.g. `Anonymice Powerline Nerd Font Complete.ttf`)?_ Bicubik-Capital, modified from Bicubik (cant find the source)
- _Which terminal emulator are you using (e.g. `iterm2`, `urxvt`, `gnome`, `konsole`)?_ kitty
- _Are you using OS X, Linux or Windows? And which specific version or distribution?_ Linux, EndeavourOS

**Comment by Finii** [comment]
```
$ fontforge -script ../../font-patcher ../../src/unpatched-fonts/Bicubik.OTF
Copyright (c) 2000-2021. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20201107
 Based on sources from 2021-01-15 15:55 UTC-ML-D-GDK3.
PythonUI_Init()
copyUIMethodsToBaseTable()
This font contains both a 'kern' table and a 'GPOS' table.
  The 'kern' table will only be read if there is no 'kern' feature in 'GPOS'.
Traceback (most recent call last):
  File "/home/fini/git/nerd-fonts/bin/scripts/../../font-patcher", line 933, in <module>
    main()
  File "/home/fini/git/nerd-fonts/bin/scripts/../../font-patcher", line 927, in main
    patcher = font_patcher()
  File "/home/fini/git/nerd-fonts/bin/scripts/../../font-patcher", line 54, in __init__
    self.sourceFont = fontforge.open(self.args.font)
OSError: Open failed
```

**Comment by Finii** [comment]
```
fontforge ../../src/unpatched-fonts/Bicubik.OTF
```
![image](https://user-images.githubusercontent.com/16012374/143178600-588ec180-d221-4c0e-953c-3e13669d6264.png)
